---
title: "Bikeshare"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(readr)
library(ggplot2)
library(plotly)
detach("package:dplyr", unload=TRUE)
library(dplyr)
library(DT)
library(leaflet)
library(lubridate)
```


```{r load_data, include=F, message=F}
trips_df <- read_csv('http://s3.amazonaws.com/assets.datacamp.com/production/course_6961/datasets/sanfran_bikeshare_joined_oneday.csv') %>%
  mutate(duration_min = duration_sec / 60,
         start_hour = hour(start_date)) %>%
  filter(duration_min <= 8 * 60) %>%
  rename(latitude = start_latitude,
         longitude = start_longitude)

stations_df <- read_csv('http://s3.amazonaws.com/assets.datacamp.com/production/course_6355/datasets/stations_data.csv')

data_date <- unique(as.Date(trips_df$start_date))



```


Sidebar {.sidebar}
=============================
### Sidebar

```{r}
sliderInput(inputId = "start_slider", 
            label = "Select trip start times to display (hour of day):", 
            min = 0, 
            max = 24, 
            value = c(7, 10), 
            step = 1)

sliderInput("duration_bin", 
            label = "Select # of minutes to bin trip durations:",
           min = 1,
           max = 15, 
           value = 1, 
           step = 1)

show_trips_df <- reactive({

  trips_df %>%
    filter(start_hour >= input$start_slider[1] &
             start_hour <= input$start_slider[2])

})


```



Overview
==========================

Column {data-width=650}
-----------------------------------------------------------------------

### Origin

```{r}

renderLeaflet({
  show_trips_df() %>%
  group_by(start_station_id, latitude, longitude) %>%
  count() %>%
  leaflet() %>%
  addTiles() %>%
  addCircles(radius = ~ n)
})


```

> Source: Bay Area Bike Share, Date: `r data_date`

Column {data-width=350}
-----------------------------------------------------------------------

### Total Tips

```{r}
renderValueBox({
  valueBox(prettyNum(show_trips_df() %>%
                     nrow(), big.mark = ','), 
         icon = 'fa-bicycle')
})

```


### Trip by Start Time

```{r}
renderPlot({
  
  show_trips_df() %>%
    mutate(hour = hour(start_date)) %>%
    group_by(hour) %>%
    summarize(total = n()) %>%
    ggplot(aes(x = hour, y = total)) +
    theme_bw() +
    geom_bar(stat = 'identity', fill = "midnightblue") +
    labs(y = "Trips Started")
})

```




Duration 
================================

### Trip Duration

```{r static_plot, fig.width = 10, fig.height = 6}

renderPlot({
  show_trips_df() %>%
  mutate(`Trip Duration (min)` = duration_sec / 60) %>%
  filter(`Trip Duration (min)` <= 60) %>%
  ggplot(aes(x = `Trip Duration (min)`)) +
  theme_bw() +
  geom_histogram(binwidth = input$duration_bin, fill = "midnightblue") +
  ylab('# Trips')
})


```





